Repository boostcampwm-2024/web25-funch, pull requests merged in 2024-11, with the labels that each got.

#58 미디어 서버 ESLint 및 Prettier 추가
  mediaServer/package-lock.json
  mediaServer/package.json
Labels: be 🐿️, setting ⚙️

#61 setting: 폰트 변수 설정
  client/src/app/fonts/BlackHanSans-Regular.ttf
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
Labels: fe 🌐, setting ⚙️

#62 setting: 폰트 className설정
  client/src/app/layout.tsx
Labels: fe 🌐, setting ⚙️

#66 setting: msw 설정
  client/package-lock.json
  client/package.json
  client/public/mockServiceWorker.js
  client/src/app/MswInitializer.tsx
  client/src/app/components/Ping.tsx
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/app/server/browser.ts
  client/src/app/server/handlers.ts
  client/src/app/server/init.ts
  client/src/app/server/node.ts
  client/tsconfig.json
Labels: fe 🌐, setting ⚙️

#67 setting: vitest 세팅
  client/package-lock.json
  client/package.json
  client/src/app/__test__/sum.test.ts
  client/src/app/categories/features/CategoryCard.tsx
  client/src/app/categories/page.tsx
  client/src/app/page.test.tsx
  client/src/app/page.tsx
  client/vitest.config.ts
  client/vitest.setup.ts
Labels: fe 🌐, setting ⚙️

#68 setting: 폰트 설정
  client/plugins/tailwind.plugin.ts
  client/src/app/page.tsx
  client/tailwind.config.ts
Labels: fe 🌐, setting ⚙️

#71 setting: 최상위 레이아웃 스타일 구성
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/tailwind.config.ts
Labels: fe 🌐, setting ⚙️

#72 feature: Toolbar UI 구성
  client/src/app/components/layout/LoginBtn.tsx
  client/src/app/components/layout/Search.tsx
  client/src/app/components/layout/StudioBtn.tsx
  client/src/app/components/layout/ThemeController.tsx
  client/src/app/components/layout/ToolBar.tsx
  client/src/app/components/svgs/MoonSvg.tsx
  client/src/app/components/svgs/StudioSvg.tsx
Labels: feature ✨, fe 🌐

#73 feat: 검색창 UI
  client/package-lock.json
  client/package.json
  client/src/app/components/layout/Header.tsx
  client/src/app/components/layout/Search.tsx
  client/src/app/components/layout/SearchView.tsx
  client/src/app/components/svgs/DeleteSvg.tsx
  client/src/app/globals.css
Labels: feature ✨, fe 🌐

#76 feature: DeemedBtn 구현
  client/src/app/components/layout/DeemedLink.tsx
  client/src/app/components/svgs/ReadingGlassSvg.tsx
  client/src/app/libs/internalTypes.ts
  client/src/app/page.tsx
Labels: feature ✨, fe 🌐

#80 feat: 홈 링크 태그에 title 속성 추가
  client/src/app/components/layout/ToolBar.tsx
Labels: feature ✨, fe 🌐

#81 feat: Badge 컴포넌트
  client/src/app/features/Badge.tsx
  client/src/app/page.tsx
Labels: feature ✨, fe 🌐

#83 feat: AccordionButton 컴포넌트
  client/src/app/components/AccordionButton.tsx
  client/src/app/components/ClientComponentForTest.tsx
  client/src/app/components/svgs/DownArrowSvg.tsx
  client/src/app/page.tsx
Labels: feature ✨, fe 🌐

#84 feat: 서랍 상단 UI 구현
  client/src/app/categories/page.tsx
  client/src/app/components/cabinet/Cabinet.tsx
  client/src/app/components/cabinet/CabinetContainer.tsx
  client/src/app/components/cabinet/CabinetLink.tsx
  client/src/app/components/cabinet/CategoryLink.tsx
  client/src/app/components/cabinet/FollowLink.tsx
  client/src/app/components/cabinet/StreamerLink.tsx
  client/src/app/components/svgs/CategorySvg.tsx
  client/src/app/components/svgs/FollowSvg.tsx
  client/src/app/layout.tsx
  client/src/app/page.tsx
Labels: feature ✨, fe 🌐

#86 feat: 서랍 상단 UI 팔로우 채널
  client/src/app/components/ClientComponentForTest.tsx
  client/src/app/components/cabinet/Cabinet.tsx
  client/src/app/components/cabinet/CabinetContainer.tsx
  client/src/app/components/cabinet/CabinetLink.tsx
  client/src/app/components/cabinet/CategoryLink.tsx
  client/src/app/components/cabinet/FollowLink.tsx
  client/src/app/components/cabinet/FollowList.tsx
  client/src/app/components/layout/DeemedLink.tsx
Labels: feature ✨, fe 🌐

#87 feat: 서랍UI 팔로잉 채널 스트리머 정보 UI 구현
  client/src/app/__mocks__/follow.ts
  client/src/app/components/cabinet/Cabinet.tsx
  client/src/app/components/cabinet/CabinetContainer.tsx
  client/src/app/components/cabinet/FollowList.tsx
  client/src/app/libs/internalTypes.ts
Labels: feature ✨, fe 🌐

#88 refactor: HeaderControlButton, Image(for test), brand 색상, useInternalRouter
  client/next.config.mjs
  client/src/app/components/layout/Header.tsx
  client/src/app/components/layout/HeaderControlButton.tsx
  client/src/app/components/layout/StudioBtn.tsx
  client/src/app/components/layout/ThemeController.tsx
  client/src/app/components/layout/ToolBar.tsx
  client/src/app/components/livesGrid/Lives.tsx
  client/src/app/components/svgs/FunchSvg.tsx
  client/src/app/components/svgs/MoonSvg.tsx
  client/src/app/components/svgs/StudioSvg.tsx
  client/src/app/globals.css
  client/src/app/hooks/useInternalRouter.ts
  client/src/app/studio/page.tsx
  client/tailwind.config.ts
Labels: refactor 🛠️, fe 🌐

#90 feat: 테마 컨텍스트
  client/src/app/GlobalProvider.tsx
  client/src/app/components/layout/HeaderControlButton.tsx
  client/src/app/components/layout/ThemeController.tsx
  client/src/app/components/livesGrid/Lives.tsx
  client/src/app/globals.css
  client/src/app/hooks/useThemeContext.ts
  client/src/app/libs/constants.ts
  client/src/app/libs/internalTypes.ts
  client/src/app/providers/ThemeProvider.tsx
  client/tailwind.config.ts
Labels: feature ✨, fe 🌐

#95 feat: 팔로잉 채널 UI 구현
  client/src/app/__mocks__/follow.ts
  client/src/app/components/cabinet/Cabinet.tsx
  client/src/app/components/cabinet/CabinetContainer.tsx
  client/src/app/components/cabinet/FollowList.tsx
  client/src/app/components/svgs/UpArrowSvg.tsx
  client/src/app/following/page.tsx
  client/src/app/hooks/useDesktop.ts
  client/src/app/libs/internalTypes.ts
Labels: feature ✨, fe 🌐

#96 feat: 팔로잉 채널 UI
  client/src/app/components/cabinet/FollowList.tsx
Labels: feature ✨, fe 🌐

#140 refactor: 서랍 UI title opacity0 -> display 변경 방식으로 변경
  client/src/app/components/cabinet/FollowList.tsx
Labels: refactor 🛠️, fe 🌐

#142 feat: live section live info 컴포넌트 UI
  client/plugins/tailwind.plugin.ts
  client/src/app/__mocks__/lives.ts
  client/src/app/components/livesGrid/LiveBadge.tsx
  client/src/app/features/Badge.tsx
  client/src/app/features/live/Live.tsx
  client/src/app/features/live/LiveSection.tsx
  client/src/app/libs/formats.ts
  client/src/app/providers/LiveProvider.tsx
Labels: feature ✨, fe 🌐

#143 feat: 시청 페이지 UI
  client/src/app/features/live/Live.tsx
  client/src/app/features/live/LiveSection.tsx
Labels: feature ✨, fe 🌐

#148 feat: PipButton UI
  client/src/app/features/live/Live.tsx
  client/src/app/features/live/LiveSection.tsx
Labels: feature ✨, fe 🌐

#149 feat: fullscreen 버튼 UI 작업 중
  client/src/app/components/svgs/FullscreenQuitSvg.tsx
  client/src/app/components/svgs/FullscreenSvg.tsx
  client/src/app/features/live/Live.tsx
  client/src/app/features/live/LiveSection.tsx
  client/src/app/features/live/VideoIconButton.tsx
  client/tailwind.config.ts
Labels: feature ✨, fe 🌐

#216 refactor: 클라이언트 디렉토리 구조 개선 및 레이아웃 분리
  client/src/__mocks__/follow.ts
  client/src/__mocks__/lives.ts
  client/src/__test__/sum.test.ts
  client/src/app/(domain)/categories/features/CategoryCard.tsx
  client/src/app/(domain)/categories/page.tsx
  client/src/app/(domain)/features/Badge.tsx
  client/src/app/(domain)/features/RecommendedLives.tsx
  client/src/app/(domain)/features/live/Live.tsx
  client/src/app/(domain)/features/live/LiveInfo.tsx
  client/src/app/(domain)/features/live/LiveSection.tsx
  client/src/app/(domain)/features/live/NoLiveContent.tsx
  client/src/app/(domain)/features/live/VideoController.tsx
  client/src/app/(domain)/features/live/VideoIconButton.tsx
  client/src/app/(domain)/following/page.tsx
  client/src/app/(domain)/layout.tsx
  client/src/app/(domain)/lives/[id]/page.tsx
  client/src/app/(domain)/page.tsx
  client/src/app/components/livesGrid/Lives.tsx
  client/src/app/layout.tsx
  client/src/app/page.test.tsx
  client/src/app/studio/layout.tsx
  client/src/assets/mocha.png
  client/src/hooks/useDesktop.ts
  client/src/hooks/useFocused.ts
  client/src/hooks/useFullscreen.ts
  client/src/hooks/useInternalRouter.ts
  client/src/hooks/useLiveContext.ts
  client/src/hooks/useMouseMovementOnElement.ts
  client/src/hooks/usePip.ts
  client/src/hooks/usePlay.ts
  client/src/hooks/useThemeContext.ts
  client/src/hooks/useUser.ts
  client/src/hooks/useUserContext.ts
  client/src/libs/constants.ts
  client/src/libs/formats.ts
  client/src/libs/internalTypes.ts
  client/src/server/browser.ts
  client/src/server/handlers.ts
  client/src/server/init.ts
  client/src/server/node.ts
  client/tsconfig.json
  client/vitest.config.ts
Labels: refactor 🛠️, fe 🌐

#218 API 서버 응답 Type 정의
  aplicationServer/src/types.ts
Labels: be 🐿️, setting ⚙️

#235 feat: MyStudioPage
  client/src/app/components/studio/StudioImageInput.tsx
  client/src/app/studio/features/my/MyStudioChat.tsx
  client/src/app/studio/features/my/MyStudioInfo.tsx
  client/src/app/studio/my/page.tsx
Labels: feature ✨, fe 🌐

#243 Github Callback URL 요청/응답 형식 및 값 변경
  applicationServer/src/auth/github/github.controller.ts
Labels: feature ✨, be 🐿️

#247 cors 오류 해결
  chatServer/main.ts
Labels: bug 🐞, be 🐿️

#248 feat: 추천 스트리머 목록
  client/src/app/components/cabinet/Cabinet.tsx
  client/src/app/components/cabinet/CabinetContainer.tsx
  client/src/app/components/cabinet/DesktopHeader.tsx
  client/src/app/components/cabinet/FollowList.tsx
  client/src/app/components/cabinet/SuggestedList.tsx
  client/src/libs/internalTypes.ts
Labels: feature ✨, fe 🌐

#293 feat: 스튜디오 드롭다운
  client/src/app/components/studio/StudioCategoryCard.tsx
  client/src/app/components/studio/StudioDropdown.tsx
  client/src/app/studio/my/features/MyStudioForm.tsx
  client/src/server/handlers.ts
Labels: feature ✨, fe 🌐

#302 feat: 채팅 개선
  client/configs/tailwind.constant.ts
  client/src/app/(domain)/features/live/Chat.tsx
  client/src/app/(domain)/features/live/LiveSection.tsx
  client/src/app/providers/LiveProvider.tsx
  client/src/hooks/useUser.ts
Labels: bug 🐞, refactor 🛠️, feature ✨, fe 🌐

#303 refactor: LiveSection
  client/package-lock.json
  client/package.json
  client/src/app/TanstackInitializer.tsx
  client/src/app/components/ErrorBoundary.tsx
  client/src/app/components/livesGrid/Lives.tsx
  client/src/app/layout.tsx
  client/src/app/providers/LiveProvider.tsx
Labels: refactor 🛠️, fe 🌐

#308 LiveInfo EventSource onmessage 및 onerror 로직 수정
  client/src/app/(domain)/features/live/LiveInfo.tsx
Labels: bug 🐞, fe 🌐
