Repository boostcampwm-2024/web25-funch, pull requests merged in 2024-12, with the labels that each got.

#316 무중단 배포를 위한 ecosystem.config.json과 쉘 스크립트 파일 작성
  deploy/funch-blue-ecosystem.config.json
  deploy/funch-deploy.sh
  deploy/funch-green-ecosystem.config.json
  deploy/media-deploy.sh
  deploy/media-ecosystem.config.json
Labels: be 🐿️, setting ⚙️

#341 feat: Search 페이지
  client/src/__mocks__/result.ts
  client/src/app/(domain)/following/features/FollowingOffair.tsx
  client/src/app/(domain)/search/feature/SearchContainer.tsx
Labels: feature ✨, fe 🌐

#339 Follow Test 코드 수정
  applicationServer/test/follow/follow.controller.spec.ts
Labels: bug 🐞, be 🐿️

#342 CI에서 테스트 실패 해결
  applicationServer/test/follow/follow.controller.spec.ts
  applicationServer/test/live/live.service.spec.ts
Labels: bug 🐞, be 🐿️

#347 feat: 스트림 키 재발급 기능
  client/src/app/studio/features/StreamSettingContainer.tsx
  client/src/libs/actions.ts
  client/src/server/handlers.ts
Labels: feature ✨, fe 🌐

#355 refactor: MyStudioForm 리팩토링
  client/src/app/components/studio/StudioMoodDropdown.tsx
  client/src/app/studio/my/features/MyStudioForm.tsx
Labels: refactor 🛠️, fe 🌐

#359 feat: 방송 정보 저장소 마이그레이션 #356
  applicationServer/src/constants.ts
  applicationServer/src/database/redis.service.ts
  applicationServer/src/live/entities/live.entity.ts
  applicationServer/src/live/live.controller.ts
  applicationServer/src/live/live.module.ts
  applicationServer/src/live/live.service.ts
  applicationServer/src/search/search.controller.ts
  applicationServer/src/search/search.module.ts
  applicationServer/src/search/search.service.ts
Labels: refactor 🛠️, be 🐿️

#361 hotfix: 스튜디오 페이지 NoPlaylist의 포지션 설정 오류 해결
  client/src/app/studio/my/features/StudioVideo.tsx
Labels: bug 🐞, fe 🌐

#366 refactor: 검색 결과에 따른 컴포넌트 렌더링
  client/src/app/(domain)/search/feature/SearchContainer.tsx
  client/src/app/components/studio/StudioMoodDropdown.tsx
Labels: refactor 🛠️, fe 🌐

#369 채팅 번역이 안되는 경우 처리
  chatServer/utils/translation.ts
Labels: bug 🐞, be 🐿️

#370 채팅 번역 기능 수정
  chatServer/utils/translation.ts
Labels: bug 🐞, be 🐿️
